resolver: lts-6.9
packages:
- '.'
flags:
  llvm-general:
    shared-llvm: true

ghc-options:
  nemish:
    -rtsopts
    -fprof-auto
    -auto-all
    -caf-all
    -fforce-recomp
extra-deps:
- llvm-general-3.5.1.2
- llvm-general-pure-3.5.1.0
extra-lib-dirs: [/usr/local/Cellar/libffi/3.0.13/lib]